version: '3'
services:

  forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      --proxy.http-bind=:8080
      --proxy.https-bind=:8081
      --proxy.upstream-url=http://superproxy.com:8080
    cap_add:
    - NET_ADMIN
    - NET_RAW
    ports:
    - "8080:8080"
    - "8081:8081"