version: '3'
services:

  forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      --proxy.bind=:8080
      --proxy.upstream-url=http://superproxy.com:8080
      --proxy.user=
      --proxy.pass=
    cap_add:
    - NET_ADMIN
    - NET_RAW
    ports:
    - "8080:8080"
    - "8443:8443"